config/routes.rb
Offlineapp::Application.routes.draw do
  resources :contacts
  match "/offline.appcache" => Rails::Offline	
  root :to => 'site#index'  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :address
  validates :email, :name, :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
	respond_to :html, :json

	def  create
		create!{new_contact_url}
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_tag(name, url, opts={})
    selected = {}
    selected[:class] = 'selected' if params[:controller].match(/^[^\/]+\/#{name}/)
    content_tag(:li, selected) { link_to name, url, opts }
 end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/contacts/new.html.erb
<article class="span8">
    <br>
<h1>New Contact</h1>
<%= form_for @contact do |f| %>
<hr>
    <div class="sideBySide">
        <div class="control-group input-prepend">
            <label>Name </label>
            <span class="add-on">@</span>
            <%= f.text_field :name , :class=>'span2', :placeholder=>'Name'%>
        </div>
        <div class="control-group input-prepend">
            <label>E-mail </label>
            <span class="add-on"><i class="icon-envelope"></i></span>
            <%= f.text_field :email , :class=>'span2', :placeholder=>'Your e-mail'%>
        </div>
    </div>
    <div class="control-group">
        <label>Address</label>
        <%= f.text_field :address , :class=>'input240'%>
    </div>
    <hr>

    <button class="btn btn-primary icoPosRight btn-large" id="submit" tabindex="4">Save</button>
<% end %>		
</article>
<div class="span7">
    <br>
    <h1>Contacts</h1>
    <hr>
    <table class="tableList">
        <thead>
            <tr>
                <th><a href="#">Name</a></th>
                <th><a href="#">Email</a></th>
                <th><a href="#">Address</a></th>
            </tr>
        </thead>
        <tbody id="contact_details">
            <tr >
                <td class="span3" colspan="3">Loading</td>           
            </tr>
        </tbody>
    </table>

</div>
<!--====== Template ======-->
<script id="contactTmpl" type="text/x-jsrender">
    <tr >
        <td class="txtLeft span3">{{>name}}</td>           
        <td class="txtLeft span3">{{>email}}</td>
        <td class="txtLeft span3">{{>address}}</td>
    </tr>    
</script>
<script type="text/javascript">
$(function(){
    loadOfflineContact();    
    renderContacts();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/offline.appcache"> 
  <head>
  	<title>Offline Web App</title>    
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>      
  </head>
<body >

<header class="headerPrincipal">
    <div class="limite">
        <h1 class="serviceName"><a href="/">Offline Web App</a></h1>
    </div>
      <menu id="menuPrincipal">        
	<ul>
            <li><%= menu_tag('Home', root_url())%></li>
            <li><%= menu_tag('Contacts', new_contact_path())%></li>
            <li class="btMenu"><a href="#" onclick="checkOnlineStatus()" id="network_status">Network status</a></li>             
            <li class="btMenu" style='margin-right: 5px;'><a href="#" onclick="checkCacheStatus()" id="cache_status">Cache status</a></li> 
        </ul>
    </menu>
</header>
<div class="container">
  	<%= yield %>
</div>
  </body>
</html>

app/views/site/index.html.erb
<br>
<div class="well">
You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.
</div>